inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
  SuggestExtensions: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 25

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true

Rails/SaveBang:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: true

Rails/NotNullColumn:
  Enabled: true

Rails/Date:
  Enabled: true

Rails/Delegate:
  Enabled: true

Rails/HttpStatus:
  Enabled: true

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Rails/ActiveSupportAliases:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: true
